import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const venues = [
    // İSTANBUL — ANADOLU YAKASI
    { name: "GOU Society", category: "bar", city: "İstanbul", district: "Kadıköy", address: "Suadiye, Vapur Yolu Sk. No:2 D:1A", googleMapsUrl: "https://maps.app.goo.gl/gouSociety", instagramUrl: "gousociety", rating: 4.8, priceLevel: 3, description: "Bağdat Cad.'nin en sofistike kokteyl&restoran adresi. Modern dünya mutfağı + imza kokteyller. Smart chic. Rezervasyon şart.", isActive: true },
    { name: "Vertical", category: "bar", city: "İstanbul", district: "Kadıköy", address: "Caddebostan, Bağdat Cd. Şerafettin Sk. 319-321C", googleMapsUrl: "https://maps.app.goo.gl/vertical", instagramUrl: "verticalistanbul", rating: 4.7, priceLevel: 2, description: "Caddebostan'ın en çok konuşulan kokteyl barı. Satsuma, Deep Berry imza içkiler. Kokteyl workshop'ları da düzenliyor.", isActive: true },
    { name: "Paolina Cocktail & Kitchen", category: "bar", city: "İstanbul", district: "Kadıköy", address: "Suadiye, Bağdat Cad.", googleMapsUrl: "https://maps.app.goo.gl/paolina", instagramUrl: "paolinacocktailbar", rating: 4.7, priceLevel: 3, description: "Bağdat Cad.'nin rafine kokteyl mutfağı. Şık iç mekan, sıcak ışıklandırma. Hem yemek hem içki için mükemmel buluşma.", isActive: true },
    { name: "Good Coffee Roasting Co.", category: "cafe", city: "İstanbul", district: "Kadıköy", address: "Osmanağa Mah. Mühürdar Cad. No:64/A", googleMapsUrl: "https://maps.app.goo.gl/goodcoffee", instagramUrl: "goodcoffeeroasting", rating: 4.6, priceLevel: 2, description: "Kadıköy specialty coffee sahnesi. Her çekirdeğin hikayesini anlatan barista kadrosu. Kahve meraklılarının adresi.", isActive: true },
    { name: "Nazende Cadde", category: "restaurant", city: "İstanbul", district: "Kadıköy", address: "Caferağa Mah. Moda Cad. No:4/D", googleMapsUrl: "https://maps.app.goo.gl/nazendecadde", instagramUrl: "nazendecadde", rating: 4.6, priceLevel: 3, description: "Michelin Bib Gourmand listesinde. Mezeleri ve samimi fine dining atmosferiyle öne çıkıyor. Akşam rezervasyon şart.", isActive: true },
    { name: "Skull & Bones", category: "bar", city: "İstanbul", district: "Beyoğlu", address: "Karaköy", googleMapsUrl: "https://maps.app.goo.gl/skullbones", instagramUrl: "skullandbonescktl", rating: 4.6, priceLevel: 2, description: "Karaköy'ün yaratıcı ve gizemli ruhu. Müzik, kokteyl ve atmosferi tek potada eriten güçlü bir bar deneyimi.", isActive: true },
    { name: "Harp Bar", category: "bar", city: "İstanbul", district: "Kadıköy", address: "Caferağa Mah. Misbah Muayyeş Sk. No:9", googleMapsUrl: "https://maps.app.goo.gl/harpbar", instagramUrl: "harpbarkadikoy", rating: 4.5, priceLevel: 2, description: "Kadıköy'ün klasik pub atmosferi. Guinness, İrlanda viskisi ve canlı spor yayınları. İstanbul'da Dublin köşesi.", isActive: true },
    { name: "Arkaoda", category: "bar", city: "İstanbul", district: "Kadıköy", address: "Caferağa Mah. Kadife Sok. No:18", googleMapsUrl: "https://maps.app.goo.gl/arkaoda", instagramUrl: "arkaoda", rating: 4.5, priceLevel: 2, description: "Canlı müzik, kokteyller ve sanatsal atmosferiyle Kadıköy gece hayatının kalbi. Hafta sonları mutlaka erken gidin.", isActive: true },
    { name: "Paper Cup", category: "cafe", city: "İstanbul", district: "Kadıköy", address: "Caferağa Mah. Moda Cad. No:18/A", googleMapsUrl: "https://maps.app.goo.gl/paperCupModa", instagramUrl: "papercupistanbul", rating: 4.7, priceLevel: 2, description: "Moda'nın ikonik specialty coffee durağı. Single origin çekirdekler, minimalist atmosfer. Her saatte kalabalık.", isActive: true },
    { name: "Zaaf İstanbul", category: "restaurant", city: "İstanbul", district: "Beşiktaş", address: "Ortaköy", googleMapsUrl: "https://maps.app.goo.gl/zaaf", instagramUrl: "zaafistanbul", rating: 4.7, priceLevel: 3, description: "Özel günler için şef restoranı. Güzel müzik, şık ambiyans, küçük bahçe. Hem lezzet hem atmosfer açısından üst seviye.", isActive: true },
    { name: "Cuma", category: "restaurant", city: "İstanbul", district: "Kadıköy", address: "Caferağa Mah. Moda", googleMapsUrl: "https://maps.app.goo.gl/cuma", instagramUrl: "cumarestoran", rating: 4.5, priceLevel: 3, description: "Moda'nın sevilen lezzet adresi. Mevsimsel menü, taze malzeme, samimi atmosfer. Uzun sohbet yemekleri için birebir.", isActive: true },
    { name: "FABESCO", category: "cafe", city: "İstanbul", district: "Kadıköy", address: "Osmanağa, Leylak Sk. 26/A", googleMapsUrl: "https://maps.app.goo.gl/fabesco", instagramUrl: "fabesco.ist", rating: 4.5, priceLevel: 2, description: "Kahvaltıdan akşam yemeğine tam gün hizmet. Yumurtalı brunch tabakları ve serpme kahvaltı ile öne çıkıyor.", isActive: true },
    { name: "mutfakkoz", category: "restaurant", city: "İstanbul", district: "Kadıköy", address: "Kozyatağı, Kaya Sultan Sokağı No:27-B", googleMapsUrl: "https://maps.app.goo.gl/mutfakkoz", instagramUrl: "mutfakkoz", rating: 4.7, priceLevel: 2, description: "Michelin Bib Gourmand. Ev yemeklerini fine dining ciddiyetiyle sunuyor. Lezzet-fiyat dengesi olağanüstü.", isActive: true },
    { name: "Tavern", category: "bar", city: "İstanbul", district: "Beyoğlu", address: "Firuzağa, Hayriye Cd. No:16/A", googleMapsUrl: "https://maps.app.goo.gl/tavern", instagramUrl: "tavernbeyoglu", rating: 4.6, priceLevel: 2, description: "Gün boyu restoran, akşam enerjisi yükselen kokteyl bar. Paylaşmalık tabaklar + yaratıcı kokteyl yorumları.", isActive: true },

    // İSTANBUL — NİŞANTAŞI / BEŞİKTAŞ / BEBEK
    { name: "Sakhalin İstanbul", category: "restaurant", city: "İstanbul", district: "Şişli", address: "Nişantaşı", googleMapsUrl: "https://maps.app.goo.gl/sakhalin", instagramUrl: "sakhalinistanbul", rating: 4.9, priceLevel: 3, description: "Gault&Millau 'Best International Brand 2025'. Şef Vladimir Mukhin imzası. Deniz ürünleri odaklı fine dining. İstanbul'un zirvesi.", isActive: true },
    { name: "Gizia Brasserie", category: "restaurant", city: "İstanbul", district: "Şişli", address: "Nişantaşı", googleMapsUrl: "https://maps.app.goo.gl/gizia", instagramUrl: "giziabrasserie", rating: 4.7, priceLevel: 3, description: "Nişantaşı'nın en zarif brasserie adresi. Dünya mutfağının seçkin lezzetleri, şık ambiyans. Özel günler için ideal.", isActive: true },
    { name: "People", category: "restaurant", city: "İstanbul", district: "Şişli", address: "Nişantaşı", googleMapsUrl: "https://maps.app.goo.gl/peopleistanbul", instagramUrl: "peopleistanbul", rating: 4.7, priceLevel: 3, description: "Farklı kültürlerden ilham alan rafine mutfak. Sade ama şık atmosfer. Nişantaşı'nın gurme adresi.", isActive: true },
    { name: "Foxy", category: "restaurant", city: "İstanbul", district: "Şişli", address: "Harbiye, Mim Kemal Öke Cd. No:1/D", googleMapsUrl: "https://maps.app.goo.gl/foxy", instagramUrl: "foxyistanbul", rating: 4.8, priceLevel: 3, description: "Michelin Guide listesinde. Taze-yerel ürünler, mevsimsel menü, şarap eşleşmeleri. Pazar kapalı. Rezervasyon şart.", isActive: true },
    { name: "Flock", category: "cafe", city: "İstanbul", district: "Şişli", address: "Teşvikiye, Hüsrev Gerede Cd. No:92/A", googleMapsUrl: "https://maps.app.goo.gl/flock", instagramUrl: "flock.istanbul", rating: 4.6, priceLevel: 2, description: "Sabah kahvesiyle başlayıp kokteylle biten tam gün deneyimi. Modern menü + specialty kahve + fırın. Teşvikiye'nin yeni gözdesi.", isActive: true },
    { name: "Zoka Nişantaşı", category: "bar", city: "İstanbul", district: "Şişli", address: "Teşvikiye, Ahmet Fetgeri Sok. No:31", googleMapsUrl: "https://maps.app.goo.gl/zoka", instagramUrl: "zokaistanbul", rating: 4.6, priceLevel: 2, description: "Kaş'tan gelen meze barı. Mevsimsel malzemelerle hazırlanan kokteyller + seçkin şaraplar. Nişantaşı'nın gizli incisi.", isActive: true },
    { name: "Lucca", category: "restaurant", city: "İstanbul", district: "Beşiktaş", address: "Bebek, Cevdet Paşa Cd. 51/A", googleMapsUrl: "https://maps.app.goo.gl/lucca", instagramUrl: "luccaistanbul", rating: 4.6, priceLevel: 3, description: "Bebek'in ikonik adresi. Modern Akdeniz mutfağı + yaratıcı kokteyl menüsü. Miksolojistlerin imzası: satsuma vodka.", isActive: true },
    { name: "5 to 12", category: "bar", city: "İstanbul", district: "Beşiktaş", address: "Bebek Mah. Cevdet Paşa Cd. No:32", googleMapsUrl: "https://maps.app.goo.gl/5to12", instagramUrl: "5to12bebek", rating: 4.7, priceLevel: 3, description: "Bebek sahil enerjisini rafine gece hayatıyla yorumluyor. İmza kokteyller + modern Akdeniz mutfağı. Gün batımı rezervasyonu altın.", isActive: true },
    { name: "Alexandra Cocktail Bar", category: "bar", city: "İstanbul", district: "Beşiktaş", address: "Arnavutköy, Bebek Arnavutköy Cd No:50", googleMapsUrl: "https://maps.app.goo.gl/alexandra", instagramUrl: "alexandracocktailbar", rating: 4.7, priceLevel: 2, description: "Arnavutköy'ün en sevilen kokteyl adresi. Enerjik atmosfer, samimi ortam. Hafta sonu mutlaka rezervasyon yapın.", isActive: true },
    { name: "Kronotrop Coffee Bar", category: "cafe", city: "İstanbul", district: "Beşiktaş", address: "Sinanpaşa Mah. Ihlamur Yolu Cad. No:6/A", googleMapsUrl: "https://maps.app.goo.gl/kronotrop", instagramUrl: "kronotrop", rating: 4.7, priceLevel: 2, description: "İstanbul specialty coffee'nin öncüsü. Türkiye'nin en iyi kahve barlarından biri olarak defalarca ödüllendirildi.", isActive: true },

    // İSTANBUL — BEYOĞLU / KARAKÖY / GALATA
    { name: "Mikla", category: "rooftop", city: "İstanbul", district: "Beyoğlu", address: "Meşrutiyet Cad. No:15, Pera", googleMapsUrl: "https://maps.app.goo.gl/mikla", instagramUrl: "miklarest", rating: 4.8, priceLevel: 3, description: "Michelin yıldızlı Şef Mehmet Gürs. Panoramik teras + imza fine dining. İstanbul'un tartışmasız en iyi rooftop restoranı.", isActive: true },
    { name: "Biz İstanbul", category: "bar", city: "İstanbul", district: "Beyoğlu", address: "Gümüşsuyu, Mete Cd. No:2 (AKM içi)", googleMapsUrl: "https://maps.app.goo.gl/bizistanbul", instagramUrl: "bizistanbul", rating: 4.8, priceLevel: 3, description: "Panoramik Boğaz manzarası + jazz gecesi (salı). İstanbul sokak lezzetlerinin modern versiyonları. Etkileyici bar bölümü.", isActive: true },
    { name: "Serica Restaurant", category: "rooftop", city: "İstanbul", district: "Beyoğlu", address: "The Bank Hotel, Bankalar Cad. Karaköy", googleMapsUrl: "https://maps.app.goo.gl/serica", instagramUrl: "sericarestaurant", rating: 4.7, priceLevel: 3, description: "The Bank Hotel'in tarihi binasında teras. Canlı ateşten coğrafya mutfağı. Panoramik İstanbul silüeti. Prestijli adres.", isActive: true },
    { name: "Pano Şaraphane", category: "bar", city: "İstanbul", district: "Beyoğlu", address: "Hüseyinağa Mah. Pano Sok. No:4", googleMapsUrl: "https://maps.app.goo.gl/pano", instagramUrl: "panosarabhane", rating: 4.3, priceLevel: 2, description: "1898'den beri İstiklal'in efsane şaraphanesi. Eski İstanbul atmosferi, zengin şarap kadrosu. Tarihi bir deneyim.", isActive: true },
    { name: "Manifest Roof", category: "rooftop", city: "İstanbul", district: "Beyoğlu", address: "Galata", googleMapsUrl: "https://maps.app.goo.gl/manifest", instagramUrl: "manifestroof", rating: 4.6, priceLevel: 2, description: "Galata'nın tarihi ruhunu modern rooftop atmosferiyle buluşturuyor. Panoramik İstanbul silüeti. Çok konuşulan yeni adres.", isActive: true },
    { name: "Lina Anatolian", category: "restaurant", city: "İstanbul", district: "Beyoğlu", address: "Karaköy, Boğaz cephesi", googleMapsUrl: "https://maps.app.goo.gl/lina", instagramUrl: "linaistanbul", rating: 4.6, priceLevel: 3, description: "Anadolu mutfağının modern yorumu. Panoramik Boğaz manzarası + rafine mutfak. Karaköy'ün yeni fine dining adresi.", isActive: true },
    { name: "Todos Los Dias", category: "cafe", city: "İstanbul", district: "Beyoğlu", address: "Asmalımescit", googleMapsUrl: "https://maps.app.goo.gl/todos", instagramUrl: "todoslosdiasist", rating: 4.6, priceLevel: 2, description: "Comfort food'un rafine versiyonu. Egg Salad Sando ve Gochujang bucatini imza tabaklar. Beyoğlu'nun tüm gün yaşayan mekânı.", isActive: true },
    { name: "Club Alice", category: "bar", city: "İstanbul", district: "Beşiktaş", address: "Etiler, Dilhayat Sk. No:15 D:1", googleMapsUrl: "https://maps.app.goo.gl/clubalice", instagramUrl: "clubaliceistanbul", rating: 4.5, priceLevel: 3, description: "Cozy'nin üst katında premium müzik&kokteyl kulübü. DJ performansları, doğum günü partileri. Etiler'in şık gece adresi.", isActive: true },

    // İZMİR — ALSANCAK / KONAK
    { name: "Coffeemamma", category: "cafe", city: "İzmir", district: "Alsancak", address: "Umurbey Mah. 1501. Sok. No:2C", googleMapsUrl: "https://maps.app.goo.gl/coffeemamma", instagramUrl: "coffeemamma", rating: 4.7, priceLevel: 2, description: "Eski tütün deposunda Alman kalite ödüllü kavurma merkezi. Kahvenizi içerken üretimi izliyorsunuz. İzmir'in en özgün kahve durağı.", isActive: true },
    { name: "Alliance Kordon", category: "restaurant", city: "İzmir", district: "Konak", address: "Atatürk Cad. Kordon No:2", googleMapsUrl: "https://maps.app.goo.gl/alliancekordon", instagramUrl: "alliancekordon", rating: 4.6, priceLevel: 3, description: "Deniz manzaralı teras, dünya mutfağı ve canlı müzik. Özel buluşmalar için İzmir'in en prestijli adresi.", isActive: true },
    { name: "1888 Bar", category: "bar", city: "İzmir", district: "Alsancak", address: "Gazi Kadın Sok. No:7 Alsancak", googleMapsUrl: "https://maps.app.goo.gl/1888bar", instagramUrl: "1888bar", rating: 4.5, priceLevel: 2, description: "Alsancak barlar sokağının en şık adresi. Yaratıcı kokteyl menüsü, canlı müzik performansları.", isActive: true },
    { name: "Improvement Bar", category: "bar", city: "İzmir", district: "Alsancak", address: "1453 Sok. Alsancak", googleMapsUrl: "https://maps.app.goo.gl/improvement", instagramUrl: "improvementbar", rating: 4.5, priceLevel: 2, description: "Alsancak'ın modern craft kokteyl barı. Titiz malzeme seçimi ve yaratıcı reçeteleriyle barlar sokağının kaliteli adresi.", isActive: true },
    { name: "Hayyam Meyhane", category: "bar", city: "İzmir", district: "Alsancak", address: "Dario Moreno Sok. Alsancak", googleMapsUrl: "https://maps.app.goo.gl/hayyam", instagramUrl: "hayyamizmir", rating: 4.4, priceLevel: 2, description: "1970'lerden bu yana Alsancak'ın en köklü meyhanesi. Klasik rakı-meze kültürü. Kişi başı 1200-1800 TL, rezervasyon şart.", isActive: true },
    { name: "Birinci Kordon Balık", category: "restaurant", city: "İzmir", district: "Konak", address: "Atatürk Cad. Kordon", googleMapsUrl: "https://maps.app.goo.gl/birincikordon", instagramUrl: "birincikordonbalik", rating: 4.5, priceLevel: 3, description: "Michelin tavsiye listesinde. Kordon'da rakı balık geleneğinin en iyi adresi. Taze deniz ürünleri, Ege mezeleri.", isActive: true },
    { name: "Varuna Gezgin", category: "bar", city: "İzmir", district: "Alsancak", address: "Kıbrıs Şehitleri Cad. Alsancak", googleMapsUrl: "https://maps.app.goo.gl/varuna", instagramUrl: "varunagezgin", rating: 4.5, priceLevel: 2, description: "Dünya mutfağı lezzetleri ve kokteyller. Ahşap bank masalar, iç ve dış bölümler. Kalabalık gruplar için birebir.", isActive: true },
    { name: "Kasap Fuat Alsancak", category: "restaurant", city: "İzmir", district: "Alsancak", address: "Alsancak", googleMapsUrl: "https://maps.app.goo.gl/kasapfuat", instagramUrl: "kasapfuatr", rating: 4.6, priceLevel: 3, description: "Michelin tavsiye listesinde. Et severlerin İzmir'deki en güvenilir adresi. Çeşme şubesiyle beraber zincirin amiral gemisi.", isActive: true },
    { name: "Soulmate Coffee", category: "cafe", city: "İzmir", district: "Alsancak", address: "Kıbrıs Şehitleri Cd. No:14 Konak", googleMapsUrl: "https://maps.app.goo.gl/soulmate", instagramUrl: "soulmatecoffee", rating: 4.5, priceLevel: 2, description: "Etiyopya, Kolombiya single origin çekirdekler. İzmir'in specialty coffee haritasında güçlü isim.", isActive: true },
    { name: "Freija Cafe", category: "cafe", city: "İzmir", district: "Alsancak", address: "Ali Çetinkaya Blv. Alsancak", googleMapsUrl: "https://maps.app.goo.gl/freija", instagramUrl: "freijacafe", rating: 4.5, priceLevel: 2, description: "İskandinav esinli, Alsancak'ın kalbinde şık kafe. Üçüncü nesil kahve demleme teknikleriyle hazırlanan içecekler.", isActive: true },

    // İZMİR — KARŞIYAKA / BOSTANLI
    { name: "Gracia Coffee Co.", category: "cafe", city: "İzmir", district: "Karşıyaka", address: "Bostanlı Mah. Nebil Susup Sok. No:130", googleMapsUrl: "https://maps.app.goo.gl/gracia", instagramUrl: "graciacoffeeco", rating: 4.8, priceLevel: 2, description: "Bostanlı'nın neredeyse kusursuz puanlı specialty kahvecisi. Minimalist tasarım + üst düzey barista bilgisi. İzmir kahve zirvesi.", isActive: true },
    { name: "Monas Art Coffee Bakery", category: "cafe", city: "İzmir", district: "Karşıyaka", address: "Donanmacı Mah. Ulvi Başman Sok. No:42", googleMapsUrl: "https://maps.app.goo.gl/monas", instagramUrl: "monasartcoffee", rating: 4.6, priceLevel: 2, description: "Sanat galerisi konseptli kafe. Yerel sanatçıların eserleri arasında kahve ve taze hamur işleri. Karşıyaka'nın en özgün mekânı.", isActive: true },
    { name: "Bernard Coffee", category: "cafe", city: "İzmir", district: "Karşıyaka", address: "Bostanlı, Karşıyaka", googleMapsUrl: "https://maps.app.goo.gl/bernard", instagramUrl: "bernardcoffeeizmir", rating: 4.6, priceLevel: 2, description: "Japon Shokupan ekmeğinden yapılan sandviçler + specialty kahve. İzmir'in Instagram'da en çok konuşulan yeni kafesi.", isActive: true },
    { name: "Karşıyaka Sahili", category: "park", city: "İzmir", district: "Karşıyaka", address: "Karşıyaka Sahil Yolu", googleMapsUrl: "https://maps.app.goo.gl/karsiyakasahil", instagramUrl: null, rating: 4.7, priceLevel: 1, description: "İzmir Körfezi'nin en sakin köşesi. Akşam yürüyüşleri, vapur manzarası. Basit ama çok romantik bir açık alan.", isActive: true },
    { name: "Rast Bira Bahçesi", category: "bar", city: "İzmir", district: "Karşıyaka", address: "Karşıyaka", googleMapsUrl: "https://maps.app.goo.gl/rast", instagramUrl: "rastbirabahcesi", rating: 4.4, priceLevel: 2, description: "Açık hava oturma bölümleri, kışın ateş çukurları. Salaş ama keyifli atmosfer. Karşıyaka'nın en samimi bar adresi.", isActive: true },
    { name: "Tuck Coffee", category: "cafe", city: "İzmir", district: "Karşıyaka", address: "Bostanlı, Bestekar Yusuf Nalkesen Sk. No:10A", googleMapsUrl: "https://maps.app.goo.gl/tuck", instagramUrl: "tuckcoffee", rating: 4.5, priceLevel: 2, description: "Asi panda logolu specialty kahveci. Kahve akademisiyle de hizmet veriyor. Bostanlı'nın en genç ve enerjik kafesi.", isActive: true },
    { name: "Hus Şarapçılık", category: "bar", city: "İzmir", district: "Urla", address: "Urla", googleMapsUrl: "https://maps.app.goo.gl/husarap", instagramUrl: "hussarapcilik", rating: 4.6, priceLevel: 3, description: "Michelin tavsiye listesinde. Urla bağlarından seçkin yerli şaraplar + gurme mezeler. Şarap kültürü arayanlar için değişmez adres.", isActive: true },

    // İZMİR — URLA / ÇEŞME / ALAÇATI
    { name: "Vino Locale", category: "restaurant", city: "İzmir", district: "Urla", address: "Urla", googleMapsUrl: "https://maps.app.goo.gl/vinolocale", instagramUrl: "vinolocaleizmir", rating: 5.0, priceLevel: 3, description: "Türkiye'nin 2 Michelin yıldızlı restoranı. Şef Ozan Kumbasar, Türk teruarı + Asya füzyon. Menü 6 haftada bir değişiyor. Rezervasyon aylarca dolu.", isActive: true },
    { name: "OD Urla", category: "restaurant", city: "İzmir", district: "Urla", address: "Urla", googleMapsUrl: "https://maps.app.goo.gl/odurla", instagramUrl: "odurla", rating: 4.8, priceLevel: 3, description: "Michelin yıldızlı. Zeytinlikler arasında çiftlik restoranı. Tarladan sofraya felsefesi. İzmir'in en değerli gastronomi deneyimi.", isActive: true },
    { name: "Teruar Urla", category: "restaurant", city: "İzmir", district: "Urla", address: "Urla", googleMapsUrl: "https://maps.app.goo.gl/teruar", instagramUrl: "teruarurla", rating: 4.7, priceLevel: 3, description: "Michelin yıldızlı. Urla bağları arasında şarap kültürüyle iç içe fine dining. Yerel üretici bağlantısıyla özgün menü.", isActive: true },
    { name: "İsabey Bağevi", category: "restaurant", city: "İzmir", district: "Urla", address: "Urla", googleMapsUrl: "https://maps.app.goo.gl/isabey", instagramUrl: "isabeybagevi", rating: 4.7, priceLevel: 3, description: "Michelin tavsiye listesinde. Hem bağ gezisi hem sofra deneyimi. Urla şarapları eşliğinde Ege mutfağının en özgün yorumu.", isActive: true },
    { name: "Amavi Alaçatı", category: "restaurant", city: "İzmir", district: "Çeşme", address: "Alaçatı Mahallesi 13003 Sokak No:1", googleMapsUrl: "https://maps.app.goo.gl/amavi", instagramUrl: "amavirestaurant", rating: 4.8, priceLevel: 3, description: "Michelin tavsiye listesinde. Odun ateşinde deniz mahsulleri + kokteyl konsepti. Zarif bahçe atmosferi. Rezervasyon zorunlu.", isActive: true },
    { name: "Avlu Alaçatı", category: "restaurant", city: "İzmir", district: "Çeşme", address: "Alaçatı, Amudya mevkii", googleMapsUrl: "https://maps.app.goo.gl/avlu", instagramUrl: "avlualacati", rating: 4.8, priceLevel: 3, description: "Gault&Millau ödüllü Şef Ahmet Horasan. Günlük avlanan deniz mahsulleri. İstakozlu Tagliatelle + Barbun Sashimi imza tabaklar.", isActive: true },
    { name: "Korto Alaçatı", category: "bar", city: "İzmir", district: "Çeşme", address: "Alaçatı, Kemal Paşa Cad. No:59", googleMapsUrl: "https://maps.app.goo.gl/korto", instagramUrl: "kortoalacati", rating: 4.7, priceLevel: 3, description: "Santorini estetiğiyle tasarlanmış avlu. Üst segment sushi + canlı müzik + Korto Signature kokteyller. Sabah 4'e kadar açık.", isActive: true },
    { name: "Sota Alaçatı", category: "restaurant", city: "İzmir", district: "Çeşme", address: "Viento Otel içi, Alaçatı", googleMapsUrl: "https://maps.app.goo.gl/sota", instagramUrl: "sotaalacati", rating: 4.7, priceLevel: 3, description: "Michelin tavsiye listesinde. En iyi kabuklu deniz ürünleri restoranı. Minimalist şıklık ve ince işçilik.", isActive: true },
    { name: "Tarla Alaçatı", category: "restaurant", city: "İzmir", district: "Çeşme", address: "Ovacık, 7152. Sokak No:145 Çeşme", googleMapsUrl: "https://maps.app.goo.gl/tarla", instagramUrl: "tarlaalacati", rating: 4.7, priceLevel: 3, description: "Miksoloji barı + odun ateşi + açık hava sinema etkinlikleri. DJ geceleri + Ege deniz ürünleri. Alaçatı'nın gizli elektronik müzik noktası.", isActive: true },
    { name: "Ortaya Alaçatı", category: "restaurant", city: "İzmir", district: "Çeşme", address: "Alaçatı", googleMapsUrl: "https://maps.app.goo.gl/ortaya", instagramUrl: "ortayaalacati", rating: 4.6, priceLevel: 3, description: "Michelin tavsiye listesinde. Paylaşım tabakları odaklı Ege mutfağı yorumu. Alaçatı'nın en samimi fine dining adresi.", isActive: true },
    { name: "Narımor", category: "restaurant", city: "İzmir", district: "Çeşme", address: "Çeşme", googleMapsUrl: "https://maps.app.goo.gl/narimor", instagramUrl: "narimor", rating: 4.7, priceLevel: 3, description: "Michelin yıldızlı. Çeşme'nin en prestijli adresi. Ege'nin taze deniz ürünleri ve mevsimsel menüsüyle tanınan şef restoranı.", isActive: true },
    { name: "La Puerta", category: "bar", city: "İzmir", district: "Konak", address: "Alsancak", googleMapsUrl: "https://maps.app.goo.gl/lapuerta", instagramUrl: "lapuertaizmir", rating: 4.4, priceLevel: 2, description: "Efes Yenilik Atölyesi özel yapım biraları + keyifli tasarım. Gündüz kafeterya, akşam bar enerjisi. Alsancak'ın sıcak köşesi.", isActive: true },

    // ANKARA — ÇANKAYA / GOP / ATAKULE
    { name: "Luigi's Ristorante Bar", category: "restaurant", city: "Ankara", district: "Çankaya", address: "Çankaya Cad. Atakule No:54", googleMapsUrl: "https://maps.app.goo.gl/luigis", instagramUrl: "luigisankara", rating: 4.7, priceLevel: 3, description: "Atakule'de şehir manzarasına karşı İtalyan mutfağı. Yüksek tavanlar, dev avizeler. Ankara'nın en gösterişli kutlama restoranı.", isActive: true },
    { name: "No4 Restaurant", category: "restaurant", city: "Ankara", district: "Çankaya", address: "The Green Park Hotel, Çankaya", googleMapsUrl: "https://maps.app.goo.gl/no4ankara", instagramUrl: "no4ankara", rating: 4.7, priceLevel: 3, description: "Ankara'nın en rafine fine dining adresi. Mevsimsel menü, yaratıcı sunumlar. Romantik akşamlar ve özel günler için en çok tercih.", isActive: true },
    { name: "Hayyami Şarap Evi", category: "bar", city: "Ankara", district: "Çankaya", address: "Tahran Caddesi No:20/A, Gaziosmanpaşa", googleMapsUrl: "https://maps.app.goo.gl/hayyami", instagramUrl: "hayyamiankara", rating: 4.6, priceLevel: 3, description: "Ankara'da şarap kültürünü zarif yemek deneyimiyle buluşturuyor. Geniş kavist + tapas ve füzyon tabaklar. GOP'un şık şarap evi.", isActive: true },
    { name: "Fige Restaurant", category: "restaurant", city: "Ankara", district: "Çankaya", address: "Gaziosmanpaşa", googleMapsUrl: "https://maps.app.goo.gl/fige", instagramUrl: "figeanakara", rating: 4.6, priceLevel: 3, description: "Haftalık canlı caz, akustik gitar ve piyano performansları. Zarif iç mekan. Müzik eşliğinde özel akşam yemeği için Ankara'nın en iyi adresi.", isActive: true },
    { name: "Zoie Brasserie & Lounge", category: "bar", city: "Ankara", district: "Çankaya", address: "Atakule", googleMapsUrl: "https://maps.app.goo.gl/zoie", instagramUrl: "zoieankara", rating: 4.5, priceLevel: 3, description: "Atakule'nin modern ve lounge odaklı barı. Luigi's'ten daha sakin, daha loş. Romantik buluşmalar için şehir manzaralı ideal nokta.", isActive: true },
    { name: "La Gioia Cafe Brasserie", category: "restaurant", city: "Ankara", district: "Çankaya", address: "Çankaya", googleMapsUrl: "https://maps.app.goo.gl/lagioia", instagramUrl: "lagioiankara", rating: 4.6, priceLevel: 3, description: "İtalyan ve Avrupa mutfağının seçkin lezzetleri. Ankara'nın en iyi fine dining restoranlarından. Özel günler için rezervasyon şart.", isActive: true },
    { name: "Kalbur Balık", category: "restaurant", city: "Ankara", district: "Çankaya", address: "Kazım Özalp Mah. Kuleli Sok. No:32", googleMapsUrl: "https://maps.app.goo.gl/kalbur", instagramUrl: "kalburbalik", rating: 4.7, priceLevel: 3, description: "1990'dan bu yana Ankara'nın en köklü balık restoranı. Balık pastırmalı patlıcan imza lezzet. Hafta sonu için aylarca önceden rezervasyon.", isActive: true },
    { name: "Cafe des Cafes", category: "cafe", city: "Ankara", district: "Çankaya", address: "Kavaklıdere, Tunalı Hilmi Cad.", googleMapsUrl: "https://maps.app.goo.gl/cafedescafes", instagramUrl: "cafedescafes", rating: 4.5, priceLevel: 2, description: "1995'ten bu yana Tunalı'nın simgesi. Fransız kafe atmosferi + 50'ler sandalyeleri + bahçe. Ankara'nın 'herkesin bildiği' klasiği.", isActive: true },
    { name: "Rispetto Coffee Co.", category: "cafe", city: "Ankara", district: "Çankaya", address: "Yukarı Bahçelievler Mah. 59. Sok. No:15C", googleMapsUrl: "https://maps.app.goo.gl/rispetto", instagramUrl: "rispettocoffee", rating: 4.7, priceLevel: 2, description: "Ankara specialty coffee'nin yükselen yıldızı. Titiz demleme, sıcak atmosfer. Coffee geek'lerin ve sakin date'lerin adresi.", isActive: true },
    { name: "Cafemiz", category: "cafe", city: "Ankara", district: "Çankaya", address: "Gaziosmanpaşa, Arjantin Cad. No:19/1", googleMapsUrl: "https://maps.app.goo.gl/cafemiz", instagramUrl: "cafemizankara", rating: 4.5, priceLevel: 2, description: "Arjantin Caddesi'nin efsane mekanı. Her yaştan kitleye hitap eden samimi atmosfer. Bahçe ayrı güzel. Ankara date turuna dahil edin.", isActive: true },
    { name: "Coffee LAB Kızılay", category: "cafe", city: "Ankara", district: "Çankaya", address: "Kızılay Bulvarı, Hilal", googleMapsUrl: "https://maps.app.goo.gl/coffeelab", instagramUrl: "coffeelabankara", rating: 4.2, priceLevel: 2, description: "4.2 puan + 2200+ yorum. Kızılay'ın kalbinde çok katlı bina + balkonlar. Öğrenci ve profesyonellerin ortak favorisi.", isActive: true },
    { name: "Kuğulu Park", category: "park", city: "Ankara", district: "Çankaya", address: "Kavaklıdere, Kuğulu Park", googleMapsUrl: "https://maps.app.goo.gl/kugulu", instagramUrl: null, rating: 4.6, priceLevel: 1, description: "Ankara'nın kalbinde yeşil vaha. Kuğular eşliğinde sabah kahvesi ya da akşam yürüyüşü. Klasik buluşma noktası.", isActive: true },
    { name: "Chalet Garden", category: "park", city: "Ankara", district: "Çankaya", address: "Etiler, Ankara", googleMapsUrl: "https://maps.app.goo.gl/chalet", instagramUrl: "chaletankara", rating: 4.5, priceLevel: 2, description: "İsviçre Alpleri esinli bahçe mekanı. Yaz aylarında gün batımından geceye uzanan enerjik ve sosyal atmosfer.", isActive: true },
    { name: "Moretenders'", category: "bar", city: "Ankara", district: "Çankaya", address: "Kavaklıdere", googleMapsUrl: "https://maps.app.goo.gl/moretenders", instagramUrl: "moretendersbar", rating: 4.6, priceLevel: 2, description: "Bartending sanatına adanmış sofistike bar. Yüksek kaliteli malzemeler ve yenilikçi reçeteler. Kokteyl tutkunlarının favorisi.", isActive: true },
  ]

  for (const venue of venues) {
    const seedId = 'seed-' + venue.name.replace(/[\s&']/g, '-').toLowerCase()
    await prisma.venue.upsert({
      where: { id: seedId },
      update: {
        ...venue,
        instagramUrl: venue.instagramUrl
          ? 'https://instagram.com/' + venue.instagramUrl
          : null,
      },
      create: {
        id: seedId,
        ...venue,
        instagramUrl: venue.instagramUrl
          ? 'https://instagram.com/' + venue.instagramUrl
          : null,
      },
    })
  }

  console.log(`✅ ${venues.length} mekan seed edildi.`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
