import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Clear existing venues and re-seed with premium data
  await prisma.venue.deleteMany({})

  const venues = [
    // ── İSTANBUL · KADİKÖY ──
    {
      name: 'Paper Cup',
      category: 'cafe',
      city: 'İstanbul',
      district: 'Kadıköy',
      address: 'Caferağa Mah. Moda Cad. No:18/A',
      rating: 4.7,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/paperCupModa',
      instagramUrl: 'https://instagram.com/papercupistanbul',
    },
    {
      name: 'Arkaoda',
      category: 'bar',
      city: 'İstanbul',
      district: 'Kadıköy',
      address: 'Caferağa Mah. Kadife Sok. No:18',
      rating: 4.5,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/arkaoda',
      instagramUrl: 'https://instagram.com/arkaoda',
    },
    {
      name: 'Moda Sahili',
      category: 'park',
      city: 'İstanbul',
      district: 'Kadıköy',
      address: 'Caferağa Mah. Moda Cad.',
      rating: 4.8,
      priceLevel: 1,
      googleMapsUrl: 'https://maps.app.goo.gl/modaSahil',
      instagramUrl: null,
    },
    {
      name: 'Good Coffee Roasting Co.',
      category: 'cafe',
      city: 'İstanbul',
      district: 'Kadıköy',
      address: 'Osmanağa Mah. Mühürdar Cad. No:64/A',
      rating: 4.6,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/goodcoffee',
      instagramUrl: 'https://instagram.com/goodcoffeeroasting',
    },
    {
      name: 'Nazende Cadde',
      category: 'restaurant',
      city: 'İstanbul',
      district: 'Kadıköy',
      address: 'Caferağa Mah. Moda Cad. No:4/D',
      rating: 4.6,
      priceLevel: 3,
      googleMapsUrl: 'https://maps.app.goo.gl/nazendecadde',
      instagramUrl: 'https://instagram.com/nazendecadde',
    },
    // ── İSTANBUL · BEŞİKTAŞ ──
    {
      name: 'Kronotrop Coffee Bar',
      category: 'cafe',
      city: 'İstanbul',
      district: 'Beşiktaş',
      address: 'Sinanpaşa Mah. Ihlamur Yolu Cad. No:6/A',
      rating: 4.7,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/kronotrop',
      instagramUrl: 'https://instagram.com/kronotrop',
    },
    {
      name: 'Abdi İpekçi Parkı',
      category: 'park',
      city: 'İstanbul',
      district: 'Beşiktaş',
      address: 'Ihlamur Yolu, Beşiktaş',
      rating: 4.6,
      priceLevel: 1,
      googleMapsUrl: 'https://maps.app.goo.gl/abdiipekci',
      instagramUrl: null,
    },
    {
      name: 'Lucca',
      category: 'restaurant',
      city: 'İstanbul',
      district: 'Beşiktaş',
      address: 'Cihannuma Mah. Muallim Naci Cad. No:51',
      rating: 4.5,
      priceLevel: 3,
      googleMapsUrl: 'https://maps.app.goo.gl/lucca',
      instagramUrl: 'https://instagram.com/luccaistanbul',
    },
    // ── İSTANBUL · BEYOĞLU ──
    {
      name: 'Mikla',
      category: 'rooftop',
      city: 'İstanbul',
      district: 'Beyoğlu',
      address: 'Meşrutiyet Cad. No:15, Pera Palas Yanı',
      rating: 4.7,
      priceLevel: 3,
      googleMapsUrl: 'https://maps.app.goo.gl/mikla',
      instagramUrl: 'https://instagram.com/miklarest',
    },
    {
      name: 'Pano Şaraphane',
      category: 'bar',
      city: 'İstanbul',
      district: 'Beyoğlu',
      address: 'Hüseyinağa Mah. Pano Sok. No:4',
      rating: 4.3,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/pano',
      instagramUrl: 'https://instagram.com/panosarabhane',
    },
    // ── İZMİR · ALSANCAK ──
    {
      name: 'Coffeemamma',
      category: 'cafe',
      city: 'İzmir',
      district: 'Alsancak',
      address: 'Umurbey Mah. 1501. Sok. No:2C',
      rating: 4.6,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/coffeemamma',
      instagramUrl: 'https://instagram.com/coffeemamma',
    },
    {
      name: 'Kordon Sahili',
      category: 'park',
      city: 'İzmir',
      district: 'Alsancak',
      address: 'Atatürk Cad. Kordon Boyu',
      rating: 4.8,
      priceLevel: 1,
      googleMapsUrl: 'https://maps.app.goo.gl/kordon',
      instagramUrl: null,
    },
    {
      name: '1888 Bar',
      category: 'bar',
      city: 'İzmir',
      district: 'Alsancak',
      address: 'Gazi Kadın Sok. No:7 Alsancak',
      rating: 4.4,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/1888bar',
      instagramUrl: 'https://instagram.com/1888bar',
    },
    {
      name: 'Alliance Kordon',
      category: 'restaurant',
      city: 'İzmir',
      district: 'Konak',
      address: 'Atatürk Cad. Kordon No:2',
      rating: 4.5,
      priceLevel: 3,
      googleMapsUrl: 'https://maps.app.goo.gl/alliancekordon',
      instagramUrl: 'https://instagram.com/alliancekordon',
    },
    // ── İZMİR · KARŞIYAKA ──
    {
      name: 'Gracia Coffee Co.',
      category: 'cafe',
      city: 'İzmir',
      district: 'Karşıyaka',
      address: 'Bostanlı Mah. Nebil Susup Sok. No:130',
      rating: 4.8,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/gracia',
      instagramUrl: 'https://instagram.com/graciacoffeeco',
    },
    {
      name: 'Monas Art Coffee Bakery',
      category: 'cafe',
      city: 'İzmir',
      district: 'Karşıyaka',
      address: 'Donanmacı Mah. Ulvi Başman Sok. No:42',
      rating: 4.5,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/monas',
      instagramUrl: 'https://instagram.com/monasartcoffee',
    },
    {
      name: 'Karşıyaka Sahili',
      category: 'park',
      city: 'İzmir',
      district: 'Karşıyaka',
      address: 'Karşıyaka Sahil Yolu',
      rating: 4.7,
      priceLevel: 1,
      googleMapsUrl: 'https://maps.app.goo.gl/karsiyakasahil',
      instagramUrl: null,
    },
    // ── ANKARA · ÇANKAYA ──
    {
      name: 'Cafe des Cafes',
      category: 'cafe',
      city: 'Ankara',
      district: 'Çankaya',
      address: 'Kavaklıdere Mah. Tunalı Hilmi Cad.',
      rating: 4.4,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/cafedescafes',
      instagramUrl: 'https://instagram.com/cafedescafes',
    },
    {
      name: 'Cafemiz',
      category: 'cafe',
      city: 'Ankara',
      district: 'Çankaya',
      address: 'Gaziosmanpaşa Mah. Arjantin Cad. No:19/1',
      rating: 4.5,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/cafemiz',
      instagramUrl: 'https://instagram.com/cafemizankara',
    },
    {
      name: 'Rispetto Coffee Co.',
      category: 'cafe',
      city: 'Ankara',
      district: 'Çankaya',
      address: 'Yukarı Bahçelievler Mah. 59. Sok. No:15C',
      rating: 4.6,
      priceLevel: 2,
      googleMapsUrl: 'https://maps.app.goo.gl/rispetto',
      instagramUrl: 'https://instagram.com/rispettocoffee',
    },
    {
      name: 'Kuğulu Park',
      category: 'park',
      city: 'Ankara',
      district: 'Çankaya',
      address: 'Kavaklıdere Mah. Kuğulu Park',
      rating: 4.6,
      priceLevel: 1,
      googleMapsUrl: 'https://maps.app.goo.gl/kugulu',
      instagramUrl: null,
    },
    {
      name: 'Kalbur Balık',
      category: 'restaurant',
      city: 'Ankara',
      district: 'Çankaya',
      address: 'Kazım Özalp Mah. Kuleli Sok. No:32',
      rating: 4.7,
      priceLevel: 3,
      googleMapsUrl: 'https://maps.app.goo.gl/kalbur',
      instagramUrl: 'https://instagram.com/kalburbalik',
    },
  ]

  await prisma.venue.createMany({ data: venues })
  console.log(`Seeded ${venues.length} venues`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
